import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import { ThemeProvider } from '@/store/theme-providers';
import { SidebarProvider } from '@/store/sidebar-provider';

import Navbar from '@/components/navbar';
import LinearGradient from '@/components/linear-gradient';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'LLM Sphere',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SidebarProvider>
            <Navbar />
            {children}
            <LinearGradient
              transitionPoint="85%"
              from="transparent"
              to="var(--gradient-to)"
            />
            <Toaster theme="system" />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
