import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import { ThemeProvider } from '@/components/theme-providers';
import LinearGradient from '@/components/linear-gradient';
import Navbar from '@/components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'LLM Sphere',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          {children}
          <LinearGradient
            height="100vh"
            transitionPoint="85%"
            from="transparent"
            to="var(--gradient-to)"
            // className="hidden"
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
